import type { Product } from "./cart-context"

export const products: Product[] = [
  {
    id: 1,
    name: "Classic White Tee",
    price: 39.99,
    category: "Tops",
    image: "/white-cotton-t-shirt.png",
    description: "Premium cotton t-shirt with a relaxed fit. Perfect for everyday wear.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 2,
    name: "Denim Jacket",
    price: 129.99,
    category: "Outerwear",
    image: "/blue-denim-jacket.jpg",
    description: "Vintage-inspired denim jacket with a modern fit. A timeless wardrobe essential.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 3,
    name: "Black Leather Boots",
    price: 189.99,
    category: "Footwear",
    image: "/black-leather-ankle-boots.jpg",
    description: "Premium leather ankle boots with a sleek silhouette. Crafted for comfort and style.",
    sizes: ["36", "37", "38", "39", "40", "41", "42"],
  },
  {
    id: 4,
    name: "Striped Linen Shirt",
    price: 69.99,
    category: "Tops",
    image: "/striped-linen-summer-shirt.jpg",
    description: "Lightweight linen shirt with classic stripes. Perfect for warm weather.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 5,
    name: "High-Waist Jeans",
    price: 89.99,
    category: "Bottoms",
    image: "/high-waist-blue-jeans.jpg",
    description: "Classic high-waist jeans with a flattering fit. Made from premium denim.",
    sizes: ["24", "26", "28", "30", "32"],
  },
  {
    id: 6,
    name: "Wool Overcoat",
    price: 249.99,
    category: "Outerwear",
    image: "/grey-wool-overcoat.jpg",
    description: "Elegant wool overcoat with a tailored silhouette. Perfect for cooler months.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 7,
    name: "Silk Blouse",
    price: 119.99,
    category: "Tops",
    image: "/cream-silk-blouse.png",
    description: "Luxurious silk blouse with a sophisticated drape. Versatile and elegant.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 8,
    name: "Sneakers",
    price: 79.99,
    category: "Footwear",
    image: "/white-minimalist-sneakers.png",
    description: "Minimalist white sneakers with premium leather uppers. Comfort meets style.",
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
  },
  {
    id: 9,
    name: "Knit Sweater",
    price: 99.99,
    category: "Tops",
    image: "/beige-knit-sweater.png",
    description: "Cozy knit sweater in a neutral tone. Perfect for layering.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 10,
    name: "Pleated Midi Skirt",
    price: 79.99,
    category: "Bottoms",
    image: "/black-pleated-midi-skirt.jpg",
    description: "Elegant pleated midi skirt with a flowing silhouette. Versatile and chic.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 11,
    name: "Trench Coat",
    price: 199.99,
    category: "Outerwear",
    image: "/beige-trench-coat.png",
    description: "Classic trench coat with timeless appeal. Water-resistant and stylish.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 12,
    name: "Leather Sandals",
    price: 59.99,
    category: "Footwear",
    image: "/tan-leather-sandals.png",
    description: "Handcrafted leather sandals with adjustable straps. Summer essential.",
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
]
